# Form implementation generated from reading ui file 'shopping.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(629, 485)
        self.listView = QtWidgets.QListView(parent=Form)
        self.listView.setGeometry(QtCore.QRect(20, 70, 591, 361))
        self.listView.setObjectName("listView")
        self.splitter = QtWidgets.QSplitter(parent=Form)
        self.splitter.setGeometry(QtCore.QRect(30, 20, 562, 28))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(parent=self.splitter)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=self.splitter)
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(parent=self.splitter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.splitter)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.splitter)
        self.label_3.setObjectName("label_3")
        self.spinBox = QtWidgets.QSpinBox(parent=self.splitter)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(parent=self.splitter)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "吴威的购物清单"))
        self.label.setText(_translate("Form", "商品名称："))
        self.label_2.setText(_translate("Form", "单价："))
        self.label_3.setText(_translate("Form", "数量："))
        self.pushButton.setText(_translate("Form", "添加列表"))

